name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
env:
  IMAGE_TAG: ${{ github.run_number }}
  
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle Wrapper
      run: chmod +x ./gradlew &&  ./gradlew build
    - name: Docker login to DockerHub  with token 
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-azure-storage-appcontainer-demo:${{ env.IMAGE_TAG }}
    - name: Build Image with latest tag  
      run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-azure-storage-appcontainer-demo:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-azure-storage-appcontainer-demo:${{ env.IMAGE_TAG }}
    - name: Push Docker image with latest tag  
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-azure-storage-appcontainer-demo:latest
  
  deploy_to_azure: ## deploy appcontainer to azure 
    needs: build_docker_image    
    permissions:
      contents: read
      id-token: write      
    runs-on: ubuntu-latest    
    steps:
      - name: Login to azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Deploy to Azure Container Instances
        run: az containerapp update --name ${{secrets.AZURE_CONTAINER_NAME}}  --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --image ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-azure-storage-appcontainer-demo:latest
       
    
    
