name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle Wrapper
      run: ./gradlew build
    - name: Docker login to DockerHub  with token 
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-azure-storage-appcontainer-demo

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-azure-storage-appcontainer-demo
